# Logistic Regression

## Importing the libraries

In [6]:
import pandas as pd
import numpy as np

## Importing the dataset

In [2]:
df=pd.read_csv('/content/breast_cancer.csv')

In [3]:
df.isnull()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0                 False            False                    False   
1                 False            False                    False   
2                 False            False                    False   
3                 False            False                    False   
4                 False            False                    False   
..                  ...              ...                      ...   
678               False            False                    False   
679               False            False                    False   
680               False            False                    False   
681               False            False                    False   
682               False            False                    False   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                       False              False                        False   
1                       False              False                        False   
2                       False              False                        False   
3                       False              False                        False   
4                       False              False                        False   
..                        ...                ...                          ...   
678                     False              False                        False   
679                     False              False                        False   
680                     False              False                        False   
681                     False              False                        False   
682                     False              False                        False   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0          False            False            False    False  False  
1          False            False            False    False  False  
2          False            False            False    False  False  
3          False            False            False    False  False  
4          False            False            False    False  False  
..           ...              ...              ...      ...    ...  
678        False            False            False    False  False  
679        False            False            False    False  False  
680        False            False            False    False  False  
681        False            False            False    False  False  
682        False            False            False    False  False  

[683 rows x 11 columns]

In [4]:
x=df.iloc[:,1:-1].values
y=df.iloc[:,-1].values

In [7]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(missing_values=np.nan,strategy='mean')
x=si.fit_transform(x)

In [8]:
print(x)

[[ 5.  1.  1. ...  3.  1.  1.]
 [ 5.  4.  4. ...  3.  2.  1.]
 [ 3.  1.  1. ...  3.  1.  1.]
 ...
 [ 5. 10. 10. ...  8. 10.  2.]
 [ 4.  8.  6. ... 10.  6.  1.]
 [ 4.  8.  8. ... 10.  4.  1.]]


## Splitting the dataset into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

## Training the Logistic Regression model on the Training set

In [10]:
from sklearn.linear_model import LogisticRegression
reg=LogisticRegression(random_state=0)
reg.fit(x_train,y_train)

LogisticRegression(random_state=0)

## Predicting the Test set results

In [11]:
y_hat=reg.predict(x_test)

In [13]:
print(np.concatenate((y_hat.reshape(len(y_hat),1),y_test.reshape(len(y_test),1)),1))

[[2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 4]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]]


## Making the Confusion Matrix

In [45]:
from sklearn.metrics import accuracy_score,confusion_matrix
print('accurary with test set={:.2f} %'.format(accuracy_score(y_test,y_hat)*100))
print(confusion_matrix(y_test,y_hat))

accurary with test set=95.62 %
[[84  3]
 [ 3 47]]


## Computing the accuracy with k-Fold Cross Validation

In [41]:
from sklearn.model_selection import cross_val_score
accuracy=cross_val_score(estimator=reg,X=x_train,y=y_train,cv=10)

In [43]:
print('Accuracy={:.2f} %'.format(accuracy.mean()*100))
print('Standard deviation={:.2f} %'.format(accuracy.std()*100))

Accuracy=96.70 %
Standard deviation=1.97 %
